### ISSUE TITLE
Wrong device for EGAVDeviceProperties::SetHDRTonemapping sanity check

### ISSUE THREAD

**Issue by jpark37** [elgatosf/capture-device-support#1]
This line should be GC4K60ProMK2, not GC4K60SPlus:
https://github.com/elgatosf/capture-device-support/blob/04201415738050b7e4e4807f8fe8d7456455e8b5/SampleCode/DriverInterface.cpp#L90

**Comment by FBirth** [comment]
Changed ✅ Thanks for spotting this.
