### ISSUE TITLE
Sign mismatch in EGAVHID::WriteHID

### ISSUE THREAD

**Issue by jpark37** [elgatosf/capture-device-support#2]
If you could change this:
`if (inMessage.size() > mHIDCaps->OutputReportByteLength-1)`

To this:
`if (inMessage.size()+1 > mHIDCaps->OutputReportByteLength)`

That seems to get rid of the warning. Seen in 32-bit build.

**Comment by FBirth** [comment]
Done

**Comment by RytoEX** [comment]
Assuming this is talking about this line:
https://github.com/elgatosf/capture-device-support/blob/8e8ccd8f223c77449ce50ae6e750c42ac8534ffa/Library/win/EGAVHIDImplementation.cpp#L198

I'm not seeing this change having been made.
